/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myclient.Pages;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;
import myclient.Sevices.ClientService;

/**
 *
 * @author PRIYARANJAN
 */
public class ChatUserInterface extends javax.swing.JFrame {

    /**
     * Creates new form ChatUserInterface
     */
    int xm = 0, ym = 0;
    ClientService cs;
    boolean isAllSelected = false;

    public ChatUserInterface() {
        initComponents();
        changePanel();
        ListUser.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }

    public void changePanel() {
        Parent.removeAll();
        Parent.repaint();
        Parent.revalidate();
        Parent.add(page1UI);
        Parent.repaint();
        Parent.revalidate();
    }

    public void sendEmoji(String name) {
        String myname = userTitle.getText().trim();
        int[] selectedId = ListUser.getSelectedIndices();
        ArrayList<String> users = new ArrayList<>();
        users.add(myname);
        for (int i = 0; i < selectedId.length; i++) {
            users.add(ListUser.getModel().getElementAt(selectedId[i]));
        }

        int jlistsize = ListUser.getModel().getSize();
        int selectedUserSize = users.size() - 1;
        String selected = "Selected";
        if (jlistsize == selectedUserSize) {
            selected = "All";
        }

        if (users.size() <= 1) {
            System.out.println("not selected user");
        } else {

            try {
                File file = new File("src/");
                String absolutepath = file.getAbsolutePath().replace("\\", "//");
                file = new File(absolutepath + "//emoji//"+name);

                cs.sendEmoji(selected, users, myname, file);

            } catch (Exception e) {
                System.out.println("Error emoji :" + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emojies12 = new javax.swing.JLabel();
        emojies13 = new javax.swing.JLabel();
        emojies14 = new javax.swing.JLabel();
        emojies15 = new javax.swing.JLabel();
        Parent = new javax.swing.JPanel();
        page1UI = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        portnumber = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        ipaddress = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        uname = new javax.swing.JTextField();
        connect = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        logout3 = new javax.swing.JLabel();
        logout4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ChatInterface = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListUser = new javax.swing.JList<>();
        textMsg = new javax.swing.JTextField();
        sendAll = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        msgarea = new javax.swing.JTextPane();
        jPanel6 = new javax.swing.JPanel();
        logout2 = new javax.swing.JLabel();
        logout1 = new javax.swing.JLabel();
        userTitle = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        userTitle1 = new javax.swing.JLabel();
        userTitle2 = new javax.swing.JLabel();
        emojies = new javax.swing.JLabel();
        emojies1 = new javax.swing.JLabel();
        emojies2 = new javax.swing.JLabel();
        emojies3 = new javax.swing.JLabel();
        emojies4 = new javax.swing.JLabel();
        emojies5 = new javax.swing.JLabel();
        emojies6 = new javax.swing.JLabel();
        emojies7 = new javax.swing.JLabel();
        emojies8 = new javax.swing.JLabel();
        emojies9 = new javax.swing.JLabel();
        emojies10 = new javax.swing.JLabel();
        emojies11 = new javax.swing.JLabel();
        emojies16 = new javax.swing.JLabel();
        emojies17 = new javax.swing.JLabel();
        emojies18 = new javax.swing.JLabel();
        emojies19 = new javax.swing.JLabel();
        emojies20 = new javax.swing.JLabel();
        emojies21 = new javax.swing.JLabel();

        emojies12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/1.png"))); // NOI18N
        emojies12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies12MouseClicked(evt);
            }
        });

        emojies13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/2.png"))); // NOI18N
        emojies13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies13MouseClicked(evt);
            }
        });

        emojies14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/3.png"))); // NOI18N
        emojies14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies14MouseClicked(evt);
            }
        });

        emojies15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/4.png"))); // NOI18N
        emojies15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies15MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Parent.setLayout(new java.awt.CardLayout());

        page1UI.setBackground(new java.awt.Color(0, 51, 51));
        page1UI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        page1UI.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                page1UIMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                page1UIMouseMoved(evt);
            }
        });
        page1UI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                page1UIMousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Port", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        portnumber.setBackground(new java.awt.Color(0, 51, 51));
        portnumber.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        portnumber.setForeground(new java.awt.Color(255, 255, 255));
        portnumber.setText("1234");
        portnumber.setBorder(null);
        portnumber.setCaretColor(new java.awt.Color(255, 255, 255));
        portnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portnumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(portnumber)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(portnumber)
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IP Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        ipaddress.setBackground(new java.awt.Color(0, 51, 51));
        ipaddress.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        ipaddress.setForeground(new java.awt.Color(255, 255, 255));
        ipaddress.setText("127.0.0.1");
        ipaddress.setBorder(null);
        ipaddress.setCaretColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ipaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ipaddress)
        );

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        uname.setBackground(new java.awt.Color(0, 51, 51));
        uname.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        uname.setForeground(new java.awt.Color(255, 255, 255));
        uname.setText("Enter username");
        uname.setBorder(null);
        uname.setCaretColor(new java.awt.Color(255, 255, 255));
        uname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                unameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                unameFocusLost(evt);
            }
        });
        uname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unameMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uname)
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uname, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        connect.setBackground(new java.awt.Color(0, 0, 0));
        connect.setFont(new java.awt.Font("MS Gothic", 3, 18)); // NOI18N
        connect.setForeground(new java.awt.Color(255, 255, 255));
        connect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        connect.setText("Connect");
        connect.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        connect.setOpaque(true);
        connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connectMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                connectMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                connectMouseReleased(evt);
            }
        });

        Login.setBackground(new java.awt.Color(0, 0, 0));
        Login.setFont(new java.awt.Font("MS Gothic", 3, 18)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("Login");
        Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Login.setOpaque(true);
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LoginMouseReleased(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(0, 0, 0));
        cancel.setFont(new java.awt.Font("MS Gothic", 3, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("Exit");
        cancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        cancel.setOpaque(true);
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelMouseReleased(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 51, 51));
        jLabel5.setFont(new java.awt.Font("MS Gothic", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Not Connected to server");
        jLabel5.setOpaque(true);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        logout3.setBackground(new java.awt.Color(0, 0, 0));
        logout3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout3.setForeground(new java.awt.Color(255, 255, 255));
        logout3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logout3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyIcons/icons8-macos-minimize-30 (1).png"))); // NOI18N
        logout3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logout3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logout3MouseReleased(evt);
            }
        });

        logout4.setBackground(new java.awt.Color(0, 0, 0));
        logout4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout4.setForeground(new java.awt.Color(255, 255, 255));
        logout4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logout4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyIcons/1qwe32.png"))); // NOI18N
        logout4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logout4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logout4MouseReleased(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("MS Gothic", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("User Congiguration");
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(476, 476, 476)
                .addComponent(logout3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout4)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout4)
                    .addComponent(logout3))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout page1UILayout = new javax.swing.GroupLayout(page1UI);
        page1UI.setLayout(page1UILayout);
        page1UILayout.setHorizontalGroup(
            page1UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(page1UILayout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addGroup(page1UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(page1UILayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(connect, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, page1UILayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(407, Short.MAX_VALUE))
        );
        page1UILayout.setVerticalGroup(
            page1UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page1UILayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(page1UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connect, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(page1UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(313, Short.MAX_VALUE))
        );

        Parent.add(page1UI, "card2");

        ChatInterface.setBackground(new java.awt.Color(255, 255, 255));

        ListUser.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ListUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListUser.setSelectionBackground(new java.awt.Color(0, 0, 153));
        jScrollPane3.setViewportView(ListUser);

        textMsg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textMsg.setForeground(new java.awt.Color(0, 0, 204));
        textMsg.setCaretColor(new java.awt.Color(204, 204, 255));

        sendAll.setBackground(new java.awt.Color(255, 255, 255));
        sendAll.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sendAll.setForeground(new java.awt.Color(255, 255, 255));
        sendAll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sendAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyIcons/send.png"))); // NOI18N
        sendAll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        sendAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendAll.setOpaque(true);
        sendAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendAllMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sendAllMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sendAllMouseReleased(evt);
            }
        });

        jScrollPane4.setBackground(new java.awt.Color(0, 51, 51));

        msgarea.setEditable(false);
        msgarea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        msgarea.setForeground(new java.awt.Color(0, 0, 153));
        jScrollPane4.setViewportView(msgarea);

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel6MouseMoved(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });

        logout2.setBackground(new java.awt.Color(0, 0, 0));
        logout2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout2.setForeground(new java.awt.Color(255, 255, 255));
        logout2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logout2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyIcons/icons8-macos-minimize-30 (1).png"))); // NOI18N
        logout2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logout2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logout2MouseReleased(evt);
            }
        });

        logout1.setBackground(new java.awt.Color(0, 0, 0));
        logout1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout1.setForeground(new java.awt.Color(255, 255, 255));
        logout1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyIcons/1qwe32.png"))); // NOI18N
        logout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logout1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logout1MouseReleased(evt);
            }
        });

        userTitle.setBackground(new java.awt.Color(153, 153, 255));
        userTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userTitle.setText("Useraname");
        userTitle.setOpaque(true);

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyIcons/pr_MVg_icon.png"))); // NOI18N
        logout.setText("Logout");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutMouseReleased(evt);
            }
        });

        userTitle1.setBackground(new java.awt.Color(153, 153, 255));
        userTitle1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userTitle1.setText("Me :");
        userTitle1.setOpaque(true);

        userTitle2.setBackground(new java.awt.Color(153, 153, 255));
        userTitle2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userTitle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyIcons/slct.png"))); // NOI18N
        userTitle2.setText("Select all");
        userTitle2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userTitle2.setOpaque(true);
        userTitle2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTitle2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logout1)
                            .addComponent(logout2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(userTitle)
                        .addComponent(userTitle1)
                        .addComponent(userTitle2)))
                .addContainerGap())
        );

        emojies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/1.png"))); // NOI18N
        emojies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojiesMouseClicked(evt);
            }
        });

        emojies1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/2.png"))); // NOI18N
        emojies1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies1MouseClicked(evt);
            }
        });

        emojies2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/3.png"))); // NOI18N
        emojies2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies2MouseClicked(evt);
            }
        });

        emojies3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/4.png"))); // NOI18N
        emojies3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies3MouseClicked(evt);
            }
        });

        emojies4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/6.png"))); // NOI18N
        emojies4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies4MouseClicked(evt);
            }
        });

        emojies5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/7.png"))); // NOI18N
        emojies5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies5MouseClicked(evt);
            }
        });

        emojies6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/8.png"))); // NOI18N
        emojies6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies6MouseClicked(evt);
            }
        });

        emojies7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/9.png"))); // NOI18N
        emojies7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies7MouseClicked(evt);
            }
        });

        emojies8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/10.png"))); // NOI18N
        emojies8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies8MouseClicked(evt);
            }
        });

        emojies9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/11.png"))); // NOI18N
        emojies9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies9MouseClicked(evt);
            }
        });

        emojies10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/12.png"))); // NOI18N
        emojies10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies10MouseClicked(evt);
            }
        });

        emojies11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/13.png"))); // NOI18N
        emojies11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies11MouseClicked(evt);
            }
        });

        emojies16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/14.png"))); // NOI18N
        emojies16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies16MouseClicked(evt);
            }
        });

        emojies17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/15.png"))); // NOI18N
        emojies17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies17MouseClicked(evt);
            }
        });

        emojies18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/16.png"))); // NOI18N
        emojies18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies18MouseClicked(evt);
            }
        });

        emojies19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/17.png"))); // NOI18N
        emojies19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies19MouseClicked(evt);
            }
        });

        emojies20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/18.png"))); // NOI18N
        emojies20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies20MouseClicked(evt);
            }
        });

        emojies21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/19.png"))); // NOI18N
        emojies21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emojies21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ChatInterfaceLayout = new javax.swing.GroupLayout(ChatInterface);
        ChatInterface.setLayout(ChatInterfaceLayout);
        ChatInterfaceLayout.setHorizontalGroup(
            ChatInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChatInterfaceLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ChatInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ChatInterfaceLayout.createSequentialGroup()
                        .addGroup(ChatInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ChatInterfaceLayout.createSequentialGroup()
                                .addComponent(textMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sendAll, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ChatInterfaceLayout.createSequentialGroup()
                                .addComponent(emojies)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies4)
                                .addGap(2, 2, 2)
                                .addComponent(emojies5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emojies21)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ChatInterfaceLayout.setVerticalGroup(
            ChatInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChatInterfaceLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ChatInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChatInterfaceLayout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ChatInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emojies, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies17, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies18, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies19, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies20, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emojies21, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ChatInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(sendAll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE))
                .addContainerGap())
        );

        Parent.add(ChatInterface, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void portnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portnumberActionPerformed

    }//GEN-LAST:event_portnumberActionPerformed

    private void unameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unameFocusGained
        if (uname.getText().equals("Enter username")) {
            uname.setText("");
        }
        //uname.setForeground(Color.white);
    }//GEN-LAST:event_unameFocusGained

    private void unameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unameFocusLost
        if (uname.getText().equals("")) {
            uname.setText("Enter username");
        }
        //uname.setForeground(Color.gray);
    }//GEN-LAST:event_unameFocusLost

    private void unameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unameMouseClicked

    }//GEN-LAST:event_unameMouseClicked

    private void unameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unameMouseEntered

    }//GEN-LAST:event_unameMouseEntered

    private void unameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unameMouseExited

    }//GEN-LAST:event_unameMouseExited

    private void connectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectMouseClicked
        String ipAddress = ipaddress.getText().trim();
        int port = Integer.parseInt(portnumber.getText().trim());
        cs = new ClientService(ipAddress, port);
        jLabel5.setText("Conected...");
    }//GEN-LAST:event_connectMouseClicked

    private void connectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectMousePressed
        connect.setBackground(Color.gray);
    }//GEN-LAST:event_connectMousePressed

    private void connectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectMouseReleased
        connect.setBackground(Color.black);
    }//GEN-LAST:event_connectMouseReleased

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        Parent.removeAll();
        Parent.repaint();
        Parent.revalidate();
        Parent.add(ChatInterface);
        Parent.repaint();
        Parent.revalidate();

        String username = uname.getText();
        userTitle.setText(username);
        cs.sendLoginMsg(username);

        cs.start();
    }//GEN-LAST:event_LoginMouseClicked

    private void LoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMousePressed
        Login.setBackground(Color.gray);
    }//GEN-LAST:event_LoginMousePressed

    private void LoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseReleased
        Login.setBackground(Color.black);
    }//GEN-LAST:event_LoginMouseReleased

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMousePressed
        cancel.setBackground(Color.gray);
    }//GEN-LAST:event_cancelMousePressed

    private void cancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseReleased
        cancel.setBackground(Color.black);
    }//GEN-LAST:event_cancelMouseReleased

    private void logout3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout3MouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_logout3MouseClicked

    private void logout3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout3MousePressed

    private void logout3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout3MouseReleased

    }//GEN-LAST:event_logout3MouseReleased

    private void logout4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_logout4MouseClicked

    private void logout4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout4MousePressed

    private void logout4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_logout4MouseReleased

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xm, y - ym);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        xm = evt.getX();
        ym = evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    private void page1UIMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_page1UIMouseDragged

    }//GEN-LAST:event_page1UIMouseDragged

    private void page1UIMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_page1UIMouseMoved

    }//GEN-LAST:event_page1UIMouseMoved

    private void page1UIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_page1UIMousePressed

    }//GEN-LAST:event_page1UIMousePressed
    
    private void sendAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendAllMouseClicked
        String myname = userTitle.getText().trim();
        int[] selectedId = ListUser.getSelectedIndices();
        ArrayList<String> users = new ArrayList<>();
        users.add(myname);
        for (int i = 0; i < selectedId.length; i++) {
            users.add(ListUser.getModel().getElementAt(selectedId[i]));
        }

        String selected = "Selected";
        if (isAllSelected) {
            selected = "All";
        }

        if (users.size() <= 1) {
            System.out.println("not selected user");
        } else {
            String msg = textMsg.getText();
            cs.sendMessage(msg, users, userTitle.getText(), selected);
        }
        textMsg.setText("");
    }//GEN-LAST:event_sendAllMouseClicked

    private void sendAllMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendAllMousePressed
        sendAll.setForeground(Color.gray);
    }//GEN-LAST:event_sendAllMousePressed

    private void sendAllMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendAllMouseReleased
        sendAll.setForeground(Color.white);
    }//GEN-LAST:event_sendAllMouseReleased

    private void logout2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout2MouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_logout2MouseClicked

    private void logout2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout2MousePressed

    private void logout2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_logout2MouseReleased

    private void logout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseClicked
        try {
            cs.sendLogoutMsg(userTitle.getText());
            changePanel();
        } catch (IOException ex) {
            System.out.println("error logout" + ex.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_logout1MouseClicked

    private void logout1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout1MousePressed

    private void logout1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_logout1MouseReleased

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        try {
            cs.sendLogoutMsg(userTitle.getText());
            changePanel();
        } catch (IOException ex) {
            System.out.println("error logout" + ex.getMessage());
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        logout.setBackground(Color.gray);
        //logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyIcons/si.png")));
        logout.setOpaque(true);
    }//GEN-LAST:event_logoutMousePressed

    private void logoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseReleased
        logout.setBackground(Color.black);
        //logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyIcons/pr_MVg_icon.png")));
        logout.setOpaque(true);
    }//GEN-LAST:event_logoutMouseReleased
    
    private void userTitle2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTitle2MouseClicked
        if (isAllSelected) {
            isAllSelected = false;
            ListUser.clearSelection();
        } else {
            isAllSelected = true;
            int begn = 0;
            int end = ListUser.getModel().getSize() - 1;
            if (end >= 0) {
                ListUser.setSelectionInterval(begn, end);
            }
        }
    }//GEN-LAST:event_userTitle2MouseClicked

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xm, y - ym);
    }//GEN-LAST:event_jPanel6MouseDragged

    private void jPanel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseMoved

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        xm = evt.getX();
        ym = evt.getY();
    }//GEN-LAST:event_jPanel6MousePressed

    private void emojiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojiesMouseClicked
        sendEmoji("1.png");
    }//GEN-LAST:event_emojiesMouseClicked

    private void emojies1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies1MouseClicked
        sendEmoji("2.png");
    }//GEN-LAST:event_emojies1MouseClicked

    private void emojies2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies2MouseClicked
        sendEmoji("3.png");
    }//GEN-LAST:event_emojies2MouseClicked

    private void emojies3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies3MouseClicked
        sendEmoji("4.png");
    }//GEN-LAST:event_emojies3MouseClicked

    private void emojies4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies4MouseClicked
        sendEmoji("6.png");
    }//GEN-LAST:event_emojies4MouseClicked

    private void emojies5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies5MouseClicked
        sendEmoji("7.png");
    }//GEN-LAST:event_emojies5MouseClicked

    private void emojies6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies6MouseClicked
        sendEmoji("8.png");
    }//GEN-LAST:event_emojies6MouseClicked

    private void emojies7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies7MouseClicked
        sendEmoji("9.png");
    }//GEN-LAST:event_emojies7MouseClicked

    private void emojies8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies8MouseClicked
        sendEmoji("10.png");
    }//GEN-LAST:event_emojies8MouseClicked

    private void emojies9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies9MouseClicked
        sendEmoji("11.png");
    }//GEN-LAST:event_emojies9MouseClicked

    private void emojies10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies10MouseClicked
       sendEmoji("12.png");
    }//GEN-LAST:event_emojies10MouseClicked

    private void emojies11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies11MouseClicked
        sendEmoji("13.png");
    }//GEN-LAST:event_emojies11MouseClicked

    private void emojies12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies12MouseClicked
        
    }//GEN-LAST:event_emojies12MouseClicked

    private void emojies13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies13MouseClicked
        
    }//GEN-LAST:event_emojies13MouseClicked

    private void emojies14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies14MouseClicked
        
    }//GEN-LAST:event_emojies14MouseClicked

    private void emojies15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies15MouseClicked
       
    }//GEN-LAST:event_emojies15MouseClicked

    private void emojies16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies16MouseClicked
        sendEmoji("14.png");
    }//GEN-LAST:event_emojies16MouseClicked

    private void emojies17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies17MouseClicked
        sendEmoji("15.png");
    }//GEN-LAST:event_emojies17MouseClicked

    private void emojies18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies18MouseClicked
        sendEmoji("16.png");
    }//GEN-LAST:event_emojies18MouseClicked

    private void emojies19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies19MouseClicked
         sendEmoji("17.png");
    }//GEN-LAST:event_emojies19MouseClicked

    private void emojies20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies20MouseClicked
        sendEmoji("18.png");
    }//GEN-LAST:event_emojies20MouseClicked

    private void emojies21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojies21MouseClicked
        sendEmoji("19.png");
    }//GEN-LAST:event_emojies21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatUserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChatInterface;
    public static javax.swing.JList<String> ListUser;
    private javax.swing.JLabel Login;
    private javax.swing.JPanel Parent;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel connect;
    private javax.swing.JLabel emojies;
    private javax.swing.JLabel emojies1;
    private javax.swing.JLabel emojies10;
    private javax.swing.JLabel emojies11;
    private javax.swing.JLabel emojies12;
    private javax.swing.JLabel emojies13;
    private javax.swing.JLabel emojies14;
    private javax.swing.JLabel emojies15;
    private javax.swing.JLabel emojies16;
    private javax.swing.JLabel emojies17;
    private javax.swing.JLabel emojies18;
    private javax.swing.JLabel emojies19;
    private javax.swing.JLabel emojies2;
    private javax.swing.JLabel emojies20;
    private javax.swing.JLabel emojies21;
    private javax.swing.JLabel emojies3;
    private javax.swing.JLabel emojies4;
    private javax.swing.JLabel emojies5;
    private javax.swing.JLabel emojies6;
    private javax.swing.JLabel emojies7;
    private javax.swing.JLabel emojies8;
    private javax.swing.JLabel emojies9;
    protected static javax.swing.JTextField ipaddress;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel logout1;
    private javax.swing.JLabel logout2;
    private javax.swing.JLabel logout3;
    private javax.swing.JLabel logout4;
    public static javax.swing.JTextPane msgarea;
    private javax.swing.JPanel page1UI;
    protected static javax.swing.JTextField portnumber;
    private javax.swing.JLabel sendAll;
    private javax.swing.JTextField textMsg;
    private javax.swing.JTextField uname;
    public static javax.swing.JLabel userTitle;
    private javax.swing.JLabel userTitle1;
    private javax.swing.JLabel userTitle2;
    // End of variables declaration//GEN-END:variables
}
